language: generic
stages:
  - compile
  - test
  - deploy
  - new stage
env:
  - FOO=one
  - FOO=two
  
# blocklist  
branches:
  except:
  - master

# safelist
branches:
  only:
  - working
  - 
jobs:
  include:
    - stage: compile
      script: date
    - stage: deploy
      script: echo$DEPLOY DEPLOY
    - stage: new stage
      script: ls;pwd;date
