language: generic
stages:
  - compile
  - test
  - deploy
  - new stage
env:
  - FOO=one
  - FOO=two
  
# blocklist  
branches:
  except:
  - master

# safelist
branches:
  only:
  - working
  - 
jobs:
  include:
    - stage: Compile
      script: date
    - stage: Test
      script: ls
    - stage: Package
      script: echo$DEPLOY DEPLOY
    - stage: Deploy
      script: ls;pwd;date
